### PR TITLE
Keep `httpEndpoint` valid

### LINKED ISSUE #181: ccloud.get_kafka_topic_output seems to always raise error 'Invalid address to set: []string{"http_endpoint"}'
### What happened?

Trying to fetch a topic using the following python:
```
ccloud.get_kafka_topic_output(
    credentials=GetKafkaTopicCredentialsArgs(
        key="<My key>",
        secret="<My secret>",
    ),
    kafka_cluster=GetKafkaTopicKafkaClusterArgs(
        id="<My cluster ID>",
    ),
    rest_endpoint="<My REST endpoint>",
    topic_name="<My topic>",
)
```

I get the following exception:
```
error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/usr/local/bin/pulumi-language-python-exec", line 197, in <module>
        loop.run_until_complete(coro)
      File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
        return future.result()
      File "/tests/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 137, in run_in_stack
        await run_pulumi_func(lambda: Stack(func))
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 51, in run_pulumi_func
        await wait_for_rpcs()
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/stack.py", line 121, in wait_for_rpcs
        raise exception
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/output.py", line 199, in run
        transformed: Input[U] = func(value)
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi_confluentcloud/_utilities.py", line 243, in <lambda>
        }).apply(lambda resolved_args: func(*resolved_args['args'],
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi_confluentcloud/get_kafka_topic.py", line 126, in get_kafka_topic
        __ret__ = pulumi.runtime.invoke('confluentcloud:index/getKafkaTopic:getKafkaTopic', __args__, opts=opts, typ=GetKafkaTopicResult).value
      File "/topic_bug/.venv/lib/python3.9/site-packages/pulumi/runtime/invoke.py", line 147, in invoke
        raise invoke_error
    Exception: invoke of confluentcloud:index/getKafkaTopic:getKafkaTopic failed: invocation of confluentcloud:index/getKafkaTopic:getKafkaTopic returned an error: invoking confluentcloud:index/getKafkaTopic:getKafkaTopic: 1 error occurred:
        * error reading Kafka Topic "<My topic name>": Invalid address to set: []string{"http_endpoint"}
```

### Expected Behavior

Successfully return information about the topic without throwing an exception

### Steps to reproduce

1. Create a python file called `__main__.py` with the following contents:
```
import pulumi_confluentcloud as ccloud
from pulumi_confluentcloud import GetKafkaTopicCredentialsArgs, \
    GetKafkaTopicKafkaClusterArgs

res = ccloud.get_kafka_topic_output(
    credentials=GetKafkaTopicCredentialsArgs(
        key="<My key>",
        secret="<My secret>",
    ),
    kafka_cluster=GetKafkaTopicKafkaClusterArgs(
        id="<My cluster ID>",
    ),
    rest_endpoint="<My REST endpoint>",
    topic_name="<My topic>",
)
```

2. Fill in the above fields (as strings) with your cluster and topic details

3. Create another file called `Pulumi.yaml` with this contents:
```
name: test
runtime:
  name: python
  options:
    virtualenv: .venv
description: A test
```

4. Run these commands:
```
# Install dependencies
python3 -m venv .venv
source .venv/bin/activate
pip install pulumi
pip install pulumi-confluentcloud

# Run pulumi script
pulumi up
```

### Output of `pulumi about`

CLI          
Version      3.74.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME            VERSION
confluentcloud  1.24.0
python          unknown

Host     
OS       darwin
Version  13.4.1
Arch     x86_64

This project is written in python: executable='/topic_bug/.venv/bin/python3' version='3.9.0
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/nicholas-ebert
User           nicholas-ebert
Organizations  nicholas-ebert, daimler-mic

Dependencies:
NAME                   VERSION
pip                    23.2.1
pulumi-confluentcloud  1.24.0
setuptools             68.0.0
wheel                  0.41.1

Pulumi locates its logs in /var/folders/zc/xwj0l22j6q13ddpft5dmbsm9xlqk42/T/ by default

### Additional context

This seems to happen regardless of if I use strings or Outputs for the fields. Also this doesn't happen if I use `await get_kafka_topic()`, but this isn't a great pattern for my use case.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by rquitales**
We do this by re-projecting the field into the TF provider (without logic) and then ensuring that the upstream provider never sees the field. This fixes #181.

We also:
- Update pu/pu to v3.78.1 for the examples test package
- Update the bridge to v3.57.0
- Add a new test to ensure our fix works as expected.

### CODE REVIEW

**Review by iwahbe — CHANGES_REQUESTED** [review]
This is very similar to what caused us problems in with `aws.rds.Instance`. Could we remove the patch all-together and apply a similar solution to https://github.com/pulumi/pulumi-aws/pull/2686 (keeping all of our code in `resources.go`).

This way there won't be any unintended interactions within the upstream provider.

**Review by iwahbe — APPROVED** [review]
I'm approving to remove the "(requested changes)" from my review, but I would like a second pair of eyes before I merge.

File: provider/resources.go [hunk 1]
```diff
@@ -90,11 +94,55 @@ func Provider() tfbridge.ProviderInfo {
...
+					endpoint, ok := config[httpEndpoint]
+					if !ok {
+						// The optional key is not present, so we can return the config as is.
+						return config, nil
+					}
+
+					// The user has set both httpEndpoint and restEndpoint. These are semantically
+					// the same, so it is forbidden to set both.
+					if _, ok := config[restEndpoint]; ok {
+						return config, fmt.Errorf(`Cannot specify both "httpEndpoint" and "restEndpoint"` +
```
Comment (guineveresaenger) [inline provider/resources.go:115]: super nitty, feel fee to ignore: since we're defining these as `const`s, let's use them here too.
```suggestion
						return config, fmt.Errorf(`Cannot specify both %s and %s` + ...`, httpEndpoint, restEndpoint
```

File: provider/resources.go [hunk 2]
```diff
@@ -90,11 +94,55 @@ func Provider() tfbridge.ProviderInfo {
...
+							`, please set only "restEndpoint"`)
+					}
+
+					tfbridge.GetLogger(ctx).Warn(`"httpEndpoint" is deprecated, use "restEndpoint" instead.`)
```
Comment (guineveresaenger) [inline provider/resources.go:119]: same here

**Review by guineveresaenger — APPROVED** [review]
Looks good to me, thank you!

I have a personal preference to using the plain string as a lookup key rather than assigning to a const but it's definitely not a blocker 😄
